Category.create(name: 'Entertainment')
Category.create(name: 'News')
Category.create(name: 'Politics')
Category.create(name: 'Sports')
Category.create(name: 'Tech')
Category.create(name: 'Video')
Category.create(name: 'World')